<?xml version="1.0"?>
<package format="3">
  <name>realgazebo_manager</name>
  <version>0.0.0</version>
  <description>RealGazebo runtime spawn/lifecycle manager</description>
  <maintainer email="kmk6061602@naver.com">kmk</maintainer>
  <license>GPL-3.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>realgazebo</exec_depend>
  <exec_depend>python3-jinja2</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
